# Generated by Django 5.2.13 on 2026-04-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='location',
            field=models.CharField(blank=True, help_text='Where the work was done — north ridge, creek lot, etc.', max_length=255),
        ),
    ]
