# Generated by Django 5.2.13 on 2026-04-10 19:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0002_timeentry_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoodInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wood_type', models.CharField(help_text='Oak, Walnut, Mixed Hardwood, etc.', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in cords', max_digits=6)),
                ('status', models.CharField(choices=[('available', 'Available'), ('spoken_for', 'Spoken For'), ('sold', 'Sold')], default='available', max_length=12)),
                ('buyer', models.CharField(blank=True, help_text="Who it's spoken for or sold to", max_length=255)),
                ('location', models.CharField(blank=True, help_text='South rack, drying shed, etc.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateField()),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_inventory', to='coop.coopmember')),
            ],
            options={
                'verbose_name_plural': 'wood inventory',
                'ordering': ['-date_added'],
            },
        ),
    ]
