# Generated by Django 5.2.13 on 2026-04-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0003_woodinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='time_end',
            field=models.TimeField(blank=True, help_text='When work ended', null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='time_start',
            field=models.TimeField(blank=True, help_text='When work started', null=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='hours',
            field=models.DecimalField(decimal_places=2, help_text='Auto-calculated from start/end times', max_digits=5),
        ),
    ]
